# Conversion
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

# Permalinks
permalink:        /:categories/:title/

# Setup
title:            'YADI ROSADI'
tagline:          'Programming, Linux and Anything'
description:      'software development, programming language, open source technology, web development tools'
url:              https://www.yadirosadi.com

author:
  name:           'Yadi Rosadi'
  email:          yadi.rosadi@gmail.com
  github:         yrsdi
  twitter:        yrsdi
  linkedin:       yadi-rosadi
  facebook:       yadi.rosadi
  url:            http://yrsdi.github.io
  email_hash:     f86c35cd9b4696694b26eb96b5c825bf
  bio:           'Full-time Operation & part-time software developer. I do what im Interest for fun and profit'

gems: 
  - jekyll-paginate
  - jemoji
  - jekyll-sitemap
  - jekyll-feed

paginate:         7

# Google Analytics
#google_analytics_tracking_id: UA-36102948-1

# Facebook Comments
#facebook_appid: 269506799827290
